### ISSUE TITLE
iobroker adapter not listed/compatible...?

### ISSUE THREAD

**Issue by peters77** [sestriel/ioBroker.ntfy#24]
I want to include notify in blockly but can't install it!?
Seems not listed/compatible.

Any chance to get it back into the list of installable plugins!?
Will it be possible to post with user:password!?

Thanks in advance.

Regards,

Christian 

<img width="500" alt="Bildschirmfoto 2024-11-03 um 20 04 57" src="https://github.com/user-attachments/assets/6b9cf424-7327-4d28-9f23-67bf7a0c6bc9">

**Comment by sestriel** [comment]
I will investigate this tomorrow evening.

Could u tell me what's ur purpose to use the authentication as user:password ?

**Comment by peters77** [comment]
Great. 👍 
As I setup a private ntfy server and expose it to the internet to get messages even not connected by private VPN I would restrict acces to my topics. 

I set up a user with password, see https://docs.ntfy.sh/config/#users-and-roles:

Example: Private instance
The easiest way to configure a private instance is to set auth-default-access to deny-all in the server.yml:

```
[/etc/ntfy/server.yml]

auth-file: "/var/lib/ntfy/user.db"
auth-default-access: "deny-all"

After that, simply create an admin user:

$ ntfy user add --role=admin phil
password: mypass
confirm: mypass
user phil added with role admin 

Once you've done that, you can publish and subscribe using [Basic Auth] with the given username/password. Be sure to use HTTPS to avoid eavesdropping and exposing your password. Here's a simple example:

curl \
    -u phil:mypass \
    -d "Look ma, with auth" \
    https://ntfy.example.com/mysecrets
```

**Comment by sestriel** [comment]
Alright i haven't read your problem right..
So ntfy will never be in the adapter list, but you can always install it manually (see screenshot 
<img width="1032" alt="screencapture_1" src="https://github.com/user-attachments/assets/d74a5257-0515-4db7-abde-52b85d83ac40">
 ). And this hasnt anything to do with compatibility. Its just the conditions for getting on the list (ex. adding a third person as administrator to your own project aka bliuefox) are that I would never agree to. I'm sorry, but this kind of thing just goes against my grain.

But about the authentication i can tell you, that you of course can use them (just see screenshot
<img width="1869" alt="screencapture_2" src="https://github.com/user-attachments/assets/f294d944-b59c-4d4e-85f4-240b5d0d4ecc">
).

**Comment by peters77** [comment]
Ah...ok. Just firgured out that I have to install it manually. Will give it a try....! Thanks for clarification...! 👍
